### ISSUE TITLE
SyntaxError: Unexpected token ...t

### ISSUE THREAD

**Issue by mirelon** [transitive-bullshit/ffmpeg-concat#10]
I think there is a typo as even running `ffmpeg-concat --version` gives me this output:
```
/usr/local/lib/node_modules/ffmpeg-concat/lib/init-frames.js:118
    ...t
    ^^^
```
The version of node js:
```
$node --version
v8.0.0
```

**Comment by transitive-bullshit** [comment]
Interesting; I can repro this on my end using node `v8.0.0`.

It's definitely not a typo, though, as if you upgrade to anything later, say `v8.8.0` or `9` or `10`, it works fine.

Node `v8` is supposed to [support](https://node.green/) this type of destructuring, so this may be some edge case issue with v8.0.0 of node, but in any case, I would recommend that you upgrade to a more recent version via `nvm`.

**Comment by mirelon** [comment]
Upgrading node version helped, thanks!

**Comment by nikitoSha** [comment]
Same problem. Node ver. is 10+

**Comment by nikitoSha** [comment]
G:\Work\Sources\Zakazi\OlodimStories\pro\olodim-stories-win-pro\bin\x86\Debug\libs\ffprobe.exe:1
	(function (exports, require, module, __filename, __dirname) { MZ�
																	^

	SyntaxError: Invalid or unexpected token
		at new Script (vm.js:79:7)
		at createScript (vm.js:251:10)
		at Object.runInThisContext (vm.js:303:10)
		at Module._compile (internal/modules/cjs/loader.js:657:28)
		at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
		at Module.load (internal/modules/cjs/loader.js:599:32)
		at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
		at Function.Module._load (internal/modules/cjs/loader.js:530:3)
		at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
		at startup (internal/bootstrap/node.js:283:19)
	G:\Work\Sources\Zakazi\OlodimStories\pro\olodim-stories-win-pro\bin\x86\Debug\libs\ffmpeg.exe:1
	(function (exports, require, module, __filename, __dirname) { MZ�
																	^

	SyntaxError: Invalid or unexpected token
		at new Script (vm.js:79:7)
		at createScript (vm.js:251:10)
		at Object.runInThisContext (vm.js:303:10)
		at Module._compile (internal/modules/cjs/loader.js:657:28)
		at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
		at Module.load (internal/modules/cjs/loader.js:599:32)
		at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
		at Function.Module._load (internal/modules/cjs/loader.js:530:3)
		at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
		at startup (internal/bootstrap/node.js:283:19)
