### ISSUE TITLE
--frame-format error

### ISSUE THREAD

**Issue by 361720691** [transitive-bullshit/ffmpeg-concat#108]
It runs correctly when I use _xvfb-run -s "-ac -screen 0 1280x1024x24" ffmpeg-concat -o all_in_one.mp4 --f jpg -T trans_temp.json 1.mp4 2.mp4 3.mp4 4.mp4_
However, in order to avoid large storage costs, I set -f jpg, I get errors like these:

# xvfb-run -s "-ac -screen 0 1280x1024x24" ffmpeg-concat -o all_in_one.mp4 -f jpg -T trans_temp.json 1.mp4 2.mp4 3.mp4 4.mp4 
{
  cmd: 'ffmpeg -i 1.mp4 -y -loglevel info -pix_fmt rgba -start_number 0 /tmp/aaf0c04dfb4bbce5a3cf54d2bfc22437/scene-0-%012d.jpg'
}
{
  cmd: 'ffmpeg -i 2.mp4 -y -loglevel info -pix_fmt rgba -start_number 0 /tmp/aaf0c04dfb4bbce5a3cf54d2bfc22437/scene-1-%012d.jpg'
}
{
  cmd: 'ffmpeg -i 4.mp4 -y -loglevel info -pix_fmt rgba -start_number 0 /tmp/aaf0c04dfb4bbce5a3cf54d2bfc22437/scene-3-%012d.jpg'
}
{
  cmd: 'ffmpeg -i 3.mp4 -y -loglevel info -pix_fmt rgba -start_number 0 /tmp/aaf0c04dfb4bbce5a3cf54d2bfc22437/scene-2-%012d.jpg'
}
{
  cmd: 'ffmpeg -ss 0.25 -i 2.mp4 -y -acodec libmp3lame -vn -t 0.5 /tmp/aaf0c04dfb4bbce5a3cf54d2bfc22437/scene-1.mp3'
}
{
  cmd: 'ffmpeg -i 1.mp4 -y -acodec libmp3lame -vn -t 1.25 /tmp/aaf0c04dfb4bbce5a3cf54d2bfc22437/scene-0.mp3'
}
{
  cmd: 'ffmpeg -ss 0.25 -i 3.mp4 -y -acodec libmp3lame -vn -t 0.7 /tmp/aaf0c04dfb4bbce5a3cf54d2bfc22437/scene-2.mp3'
}
{
  cmd: 'ffmpeg -ss 0.25 -i 4.mp4 -y -acodec libmp3lame -vn -t 3.183 /tmp/aaf0c04dfb4bbce5a3cf54d2bfc22437/scene-3.mp3'
}
init-frames: 2.791s
render 0%
render 9%
ffmpeg-concat: 12.772s
concat error TypeError: this._relink is not a function
    at Shader.proto.bind (/root/.npm-global/lib/node_modules/ffmpeg-concat/node_modules/gl-shader/index.js:31:10)
    at Object.draw (/root/.npm-global/lib/node_modules/ffmpeg-concat/node_modules/gl-transition/lib/index.js:53:14)
    at Object.draw (/root/.npm-global/lib/node_modules/ffmpeg-concat/lib/transition.js:58:18)
    at async AsyncFunction.module.exports.renderFrame (/root/.npm-global/lib/node_modules/ffmpeg-concat/lib/render-frames.js:76:5)
(node:4175) UnhandledPromiseRejectionWarning: TypeError: this._relink is not a function
    at Shader.proto.bind (/root/.npm-global/lib/node_modules/ffmpeg-concat/node_modules/gl-shader/index.js:31:10)
    at Object.draw (/root/.npm-global/lib/node_modules/ffmpeg-concat/node_modules/gl-transition/lib/index.js:53:14)
    at Object.draw (/root/.npm-global/lib/node_modules/ffmpeg-concat/lib/transition.js:58:18)
    at async AsyncFunction.module.exports.renderFrame (/root/.npm-global/lib/node_modules/ffmpeg-concat/lib/render-frames.js:76:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4175) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4175) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by TejasBob** [comment]
did you find any solution for this? I'm also facing same problem for png frameFormat.

**Comment by 712163** [comment]
> did you find any solution for this? I'm also facing same problem for png frameFormat.

Me too.
