### ISSUE TITLE
Video frame is freesed for 2nd video

### ISSUE THREAD

**Issue by mayank1513** [transitive-bullshit/ffmpeg-concat#120]
Hi,

I am trying to join 3 videos. It works well for the first and last video but the middle video frame is stuck... Middle video dimension is slightly different by 10-20 px. 720p for 1st and last, but 680x1280 for middle

**Comment by mayank1513** [comment]
ffmpeg-concat: 328444.561ms
concat error Error: ffmpeg exited with code 69: Conversion failed!

    at ChildProcess.<anonymous> (C:\Users\HariC\AppData\Roaming\npm\pnpm-global\5\node_modules\.pnpm\fluent-ffmpeg@2.1.2\node_modules\fluent-ffmpeg\lib\processor.js:182:22)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
(node:4016) UnhandledPromiseRejectionWarning: Error: ffmpeg exited with code 69: Conversion failed!
# error log

    at ChildProcess.<anonymous> (C:\Users\HariC\AppData\Roaming\npm\pnpm-global\5\node_modules\.pnpm\fluent-ffmpeg@2.1.2\node_modules\fluent-ffmpeg\lib\processor.js:182:22)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
(node:4016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch btch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--dled-unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4016) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the  the Node.js process with a non-zero exit code.
