### ISSUE TITLE
On Linux (Ubuntu 16.04 LTS) with shell_exec() command i am getting an error.

### ISSUE THREAD

**Issue by ahmadlatif1084** [transitive-bullshit/ffmpeg-concat#30]
{ cmd: 'ffmpeg -i /var/www/html/testing_video/3.mp4 -y -pix_fmt rgba -start_number 0 /tmp/eb9e2ea882c1871dd237e7a888be1c06/scene-2-%012d.raw' }
{ cmd: 'ffmpeg -i /var/www/html/testing_video/1.mp4 -y -pix_fmt rgba -start_number 0 /tmp/eb9e2ea882c1871dd237e7a888be1c06/scene-0-%012d.raw' }
{ cmd: 'ffmpeg -i /var/www/html/testing_video/2.mp4 -y -pix_fmt rgba -start_number 0 /tmp/eb9e2ea882c1871dd237e7a888be1c06/scene-1-%012d.raw' }
init-frames: 4395.999ms
ffmpeg-concat: 4496.324ms
concat error Error: failed to create OpenGL context
    at module.exports (/usr/lib/node_modules/ffmpeg-concat/lib/context.js:22:11)
    at module.exports (/usr/lib/node_modules/ffmpeg-concat/lib/render-frames.js:19:21)
    at module.exports (/usr/lib/node_modules/ffmpeg-concat/lib/index.js:47:32)
    at 
(node:5372) UnhandledPromiseRejectionWarning: Error: failed to create OpenGL context
    at module.exports (/usr/lib/node_modules/ffmpeg-concat/lib/context.js:22:11)
    at module.exports (/usr/lib/node_modules/ffmpeg-concat/lib/render-frames.js:19:21)
    at module.exports (/usr/lib/node_modules/ffmpeg-concat/lib/index.js:47:32)
    at 
(node:5372) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:5372) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by transitive-bullshit** [comment]
please only open one issue at a time if you're having a problem.
