### ISSUE TITLE
UnhandledPromiseRejectionWarning error on CLI

### ISSUE THREAD

**Issue by jl-ib** [transitive-bullshit/ffmpeg-concat#40]
Hi! I'm trying to use the library on node and on the CLI, I'm getting the same error in both cases.

This is the command I'm running on terminal:
`$ ffmpeg-concat -t circleopen -d 1000 -o test.mp4 0.mp4 1.mp4`

Using
macOS High Sierra 10.13.6
node v10.15.3

Sorry if it's a noob issue but I haven't found anything guiding me to what I'm doing wrong

Output:
```
ffmpeg-concat: 32.939ms
concat error { Error: spawn ffprobe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ffprobe',
  path: 'ffprobe',
  spawnargs:
   [ '-print_format',
     'json',
     '-show_error',
     '-show_format',
     '-show_streams',
     '0.mp4' ],
  stdout: '',
  stderr: '',
  failed: true,
  signal: null,
  cmd:
   'ffprobe -print_format json -show_error -show_format -show_streams 0.mp4',
  timedOut: false,
  killed: false }
(node:96785) UnhandledPromiseRejectionWarning: Error: spawn ffprobe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
(node:96785) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:96785) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by transitive-bullshit** [comment]
This error is saying that `ffprobe` isn't found on your system. `ffprobe` is one of the commandline programs installed when you install `ffmpeg`.

To fix this, please install `ffmpeg` and make sure it runs correctly before trying to use this library.

Thanks!

**Comment by jl-ib** [comment]
I thought it was installed when installing the package through npm, my bad, it's working now, thanks for the quick response!
