### ISSUE TITLE
Cannot find ffprobe

### ISSUE THREAD

**Issue by tarun-yrals** [transitive-bullshit/ffmpeg-concat#48]
Command :- ffmpeg-concat -t circleopen -d 750 -o final.mp4 zoom.mp4 zoom1.mp4

ffmpeg-concat: 43.491ms
concat error { Error: spawn ffprobe ENOENT
at _errnoException (util.js:1022:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
at onErrorNT (internal/child_process.js:372:16)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickCallback (internal/process/next_tick.js:180:9)
at Function.Module.runMain (module.js:695:11)
at startup (bootstrap_node.js:188:16)
at bootstrap_node.js:609:3
code: 'ENOENT',
errno: 'ENOENT',
syscall: 'spawn ffprobe',
path: 'ffprobe',
spawnargs:
[ '-print_format',
'json',
'-show_error',
'-show_format',
'-show_streams',
'zoom.mp4' ],
stdout: '',
stderr: '',
failed: true,
signal: null,
cmd: 'ffprobe -print_format json -show_error -show_format -show_streams zoom.mp4',
timedOut: false,
killed: false }
(node:20017) UnhandledPromiseRejectionWarning: Error: spawn ffprobe ENOENT
at _errnoException (util.js:1022:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
at onErrorNT (internal/child_process.js:372:16)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickCallback (internal/process/next_tick.js:180:9)
at Function.Module.runMain (module.js:695:11)
at startup (bootstrap_node.js:188:16)
at bootstrap_node.js:609:3
(node:20017) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:20017) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Could anybody help me with this problem,

**Comment by transitive-bullshit** [comment]
The error is saying that it can't find `ffprobe` (which comes with ffmpeg). Make sure `ffmpeg` is installed and added to your PATH and that you can run `ffprobe` from the command-line.

**Comment by NyWn** [comment]
If on Mac - run `brew install ffmpeg` to add ffmpeg and ffprobe to path. After installing, the example command should work.
