### ISSUE TITLE
concat error Error: failed to create OpenGL context

### ISSUE THREAD

**Issue by convertdaily** [transitive-bullshit/ffmpeg-concat#5]
**Hi i got this error, i don't have any idea about how to fix it:**
**I used this command:** ffmpeg-concat -t fade -d 500 -o test.mp4 job.mp4

 cmd: 'ffmpeg -i test.mp4 -y -pix_fmt rgba -start_number 0 /tmp/43dc39c673c7ec15c4af716423d9af17/scene-1-%012d.raw' } init-frames: 9202.664ms concat 

error Error: failed to create OpenGL context at module.exports (/usr/lib/node_modules/ffmpeg-concat/lib/context.js:22:11) 
at module.exports (/usr/lib/node_modules/ffmpeg-concat/lib/render-frames.js:19:21) 
at module.exports (/usr/lib/node_modules/ffmpeg-concat/lib/index.js:44:30) 
at <anonymous> (node:15718) UnhandledPromiseRejectionWarning: 

Error: failed to create OpenGL context 
at module.exports (/usr/lib/node_modules/ffmpeg-concat/lib/context.js:22:11) 
at module.exports (/usr/lib/node_modules/ffmpeg-concat/lib/render-frames.js:19:21) 
at module.exports (/usr/lib/node_modules/ffmpeg-concat/lib/index.js:44:30) 
at <anonymous> (node:15718) UnhandledPromiseRejectionWarning: Unhandled promise rejection. 

This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4) (node:15718) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**I am using Debian 9, node v9.11.1, npm v5.8.0, i have mesa and xvfb installed.**

**Comment by transitive-bullshit** [comment]
How are you invoking `xvfb`? Is the `DISPLAY` env variable set appropriately?

My guess is that xbfb isn't setup properly.
