### ISSUE TITLE
Error during process

### ISSUE THREAD

**Issue by galipmedia** [transitive-bullshit/ffmpeg-concat#55]
I am getting the following error. It makes the /tmp folder full of raw files then deletes it but doesn't work...
```{ cmd:
   'ffmpeg -i 1572676384712.mp4 -y -pix_fmt rgba -start_number 0 /tmp/bdc1a01d2af4e692f7bddc531f4be320/scene-0-%012d.raw' }
{ cmd:
   'ffmpeg -i 1572676446286.mp4 -y -pix_fmt rgba -start_number 0 /tmp/bdc1a01d2af4e692f7bddc531f4be320/scene-1-%012d.raw' }
init-frames: 7154.286ms
render-frames: 180.134ms
ffmpeg-concat: 8180.844ms
(node:11988) UnhandledPromiseRejectionWarning: Error: ffmpeg exited with code 1: /tmp/bdc1a01d2af4e692f7bddc531f4be320/%012d.raw: No such file or directory

    at ChildProcess.<anonymous> (/home/ct/Dev/ffmpeg/node-streamlink/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
(node:11988) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11988) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by galipmedia** [comment]
I figured out it was my input videos. Tried with other mp4s and it works fine. I am generating those videos using streamlink and they they m to be ok, they play fine, they make the /tmp files fine. Any idea what might be the issue?

**Comment by transitive-bullshit** [comment]
I just added a new `--verbose` flag which should help debug cases like these.

As far as what could be the problem, I have no idea -- ffmpeg and video formats are very complex.
