### ISSUE TITLE
Error output when using ffmpeg-concat

### ISSUE THREAD

**Issue by patmarion** [transitive-bullshit/ffmpeg-concat#6]
Here is the output.  I can confirm there there are frames for both `scene-0` and `scene-1` under `/tmp/762eca812ec43c73ae8b96ef24e1c1eb`.  Any idea what might have gone wrong?  For some reason it tries to open the non-existing file `scene-1-000000000NaN.raw`.

```
$ ffmpeg-concat -t fade -d 250 -o output.mp4 one.mp4 two.mp4
{ cmd: 'ffmpeg -i two.mp4 -y -pix_fmt rgba -start_number 0 /tmp/762eca812ec43c73ae8b96ef24e1c1eb/scene-1-%012d.raw' }
{ cmd: 'ffmpeg -i one.mp4 -y -pix_fmt rgba -start_number 0 /tmp/762eca812ec43c73ae8b96ef24e1c1eb/scene-0-%012d.raw' }
init-frames: 3702.817ms
concat error { Error: ENOENT: no such file or directory, open '/tmp/762eca812ec43c73ae8b96ef24e1c1eb/scene-1-000000000NaN.raw'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at module.exports (/home/pat/.nvm/versions/node/v8.11.1/lib/node_modules/ffmpeg-concat/lib/get-pixels.js:15:21)
    at Object.draw (/home/pat/.nvm/versions/node/v8.11.1/lib/node_modules/ffmpeg-concat/lib/transition.js:48:28)
    at <anonymous>
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/tmp/762eca812ec43c73ae8b96ef24e1c1eb/scene-1-000000000NaN.raw' }
(node:110396) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/tmp/762eca812ec43c73ae8b96ef24e1c1eb/scene-1-000000000NaN.raw'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at module.exports (/home/pat/.nvm/versions/node/v8.11.1/lib/node_modules/ffmpeg-concat/lib/get-pixels.js:15:21)
    at Object.draw (/home/pat/.nvm/versions/node/v8.11.1/lib/node_modules/ffmpeg-concat/lib/transition.js:48:28)
    at <anonymous>
(node:110396) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)
(node:110396) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by transitive-bullshit** [comment]
It looks like it's failing to compute the fps properly.

Can you send me the mp4 files you're using?  `fisch0920@gmail.com`

**Comment by patmarion** [comment]
Unfortunately the videos are for an internal project and I can't share them.  They were encoded with the command:

```
# encode frames into a 30 fps video
ffmpeg -r 30 -i frame_%07d.png -vcodec libx264 -preset fast -pix_fmt yuv420p -crf 18 output.mp4
```

Anyway, thanks for responding!  Instead of `ffmpeg-concat` I am now successfully using your ffmpeg filter here:

https://github.com/transitive-bullshit/ffmpeg-gl-transition

Thanks for providing this!

**Comment by transitive-bullshit** [comment]
No worries && thanks for the report.

I'll try to reproduce it on my end when I have some free time.

Cheers!

**Comment by brentjanderson** [comment]
I'm having the same issue, and for me it's due to a clip that is zero seconds long (due to a bug on my part).

**Comment by transitive-bullshit** [comment]
If anyone else runs into this problem, please open a new issue with more details and a repro case. Thanks!
