### ISSUE TITLE
Small test not working...

### ISSUE THREAD

**Issue by anonymousperson1209** [transitive-bullshit/ffmpeg-concat#68]
I am testing this package. I have the following:
``` javascript
const concat = require('ffmpeg-concat');

(async () => {
    await concat({
        output: 'output.mp4',
        videos: [
            'https://external-preview.redd.it/VWpo7hMi7ZwymyI4l9zd3t0pSTGiIfbXxLX7TekcwH4.gif?s=34a33f2dce0d7ae51af89dcb6b5d7cb0ea26f4a0',
            'https://external-preview.redd.it/ooH-WpKePd8qLx7Bv2sqL3mvVxo-wGfzorbJdFfxTnE.gif?s=3a46d510c2b412941626dbdcef980391bc8c19f4'
        ],
        transition: {
            name: 'directionalwipe',
            duration: 500
        },
        tempDir: 'tmp'
    });
})();
```
It results in:
```
{
  cmd: 'ffmpeg -i https://external-preview.redd.it/VWpo7hMi7ZwymyI4l9zd3t0pSTGiIfbXxLX7TekcwH4.gif?s=34a33f2dce0d7ae51af89dcb6b5d7cb0ea26f4a0 -y -pix_fmt rgba -start_number 0 tmp\\scene-0-%012d.raw'
}
{
  cmd: 'ffmpeg -i https://external-preview.redd.it/ooH-WpKePd8qLx7Bv2sqL3mvVxo-wGfzorbJdFfxTnE.gif?s=3a46d510c2b412941626dbdcef980391bc8c19f4 -y -pix_fmt rgba -start_number 0 tmp\\scene-1-%012d.raw'
}
ffmpeg-concat: 25699.550ms
(node:13852) UnhandledPromiseRejectionWarning: Error: ffmpeg exited with code 1: av_interleaved_write_frame(): I/O error
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.16 bitrate=N/A speed=N/A
video:434kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

    at ChildProcess.<anonymous> (C:\dir\node_modules\fluent-ffmpeg\lib\processor.js:182:22)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
(node:13852) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, 
or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13852) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

What am I doing incorrectly here?

**Comment by transitive-bullshit** [comment]
Hey, thanks for the concrete repro scenario.

I'm able to reproduce the issue. It seems that `ffmpeg-probe` is returning invalid info for these two videos because they are actually GIFs and we're expecting the inputs to be videos.

If someone wants to add GIF support, it shouldn't be too difficult but for now I'll just add a better error message to `ffmpeg-concat` for this case.

One workaround would be to convert your inputs to mp4 before running `ffmpeg-concat`.

Thanks!

**Comment by anonymousperson1209** [comment]
So luckily the Reddit videos can often be accessed as `.mp4`s. I tried this:
``` javascript
const concat = require('ffmpeg-concat');

(async () => {
    await concat({
        output: 'output.mp4',
        videos: [
            'https://external-preview.redd.it/VWpo7hMi7ZwymyI4l9zd3t0pSTGiIfbXxLX7TekcwH4.gif?format=mp4&s=0f30a11a312a47912081bb8994bcf6a4c3eba6b0',
            'https://external-preview.redd.it/ooH-WpKePd8qLx7Bv2sqL3mvVxo-wGfzorbJdFfxTnE.gif?format=mp4&s=5a17f7aab1baf53d5ccdfaa4e5972f63b4368f6c'
        ],
        transition: {
            name: 'directionalwipe',
            duration: 500
        },
        tempDir: 'tmp'
    });
})();
```
But I get:
```
{
  cmd: 'ffmpeg -i https://external-preview.redd.it/VWpo7hMi7ZwymyI4l9zd3t0pSTGiIfbXxLX7TekcwH4.gif?format=mp4&s=0f30a11a312a47912081bb8994bcf6a4c3eba6b0 -y -pix_fmt rgba -start_number 0 tmp\\scene-0-%012d.raw'
}
{
  cmd: 'ffmpeg -i https://external-preview.redd.it/ooH-WpKePd8qLx7Bv2sqL3mvVxo-wGfzorbJdFfxTnE.gif?format=mp4&s=5a17f7aab1baf53d5ccdfaa4e5972f63b4368f6c -y -pix_fmt rgba -start_number 0 tmp\\scene-1-%012d.raw'
}
ffmpeg-concat: 1849.706ms
(node:10948) UnhandledPromiseRejectionWarning: Error: ffmpeg exited with code 1: av_interleaved_write_frame(): I/O error
frame=   17 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.17 bitrate=N/A dup=16 drop=0 speed=N/A
video:7371kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

    at ChildProcess.<anonymous> (C:\dir\node_modules\fluent-ffmpeg\lib\processor.js:182:22)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
(node:10948) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, 
or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10948) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Before using this package, I scanned through and found a file that's purpose was determining file types from URLs. It simply took everything after the last period of the path itself. As you can see from these `.mp4` endpoints, the URL still ends in `.gif`. This is why I initially tried using the package with `.gif` files--I was afraid this package would think the `.mp4`s were `.gif`s. I am assuming that is what's happening here.

So, I have used a package to manually download the videos from the `.mp4` endpoint **as `.mp4`s**, and then send those file paths into `ffmpeg-concat`. Here's what that looks like in essence:
``` javascript
const concat = require('ffmpeg-concat');

(async () => {
    await concat({
        output: 'output.mp4',
        videos: [
            './dir/0.mp4',
            './dir/1.mp4'
        ],
        transition: {
            name: 'directionalwipe',
            duration: 500
        },
        tempDir: 'tmp'
    });
})();
```
It results in:
```
{
  cmd: 'ffmpeg -i ./dir/0.mp4 -y -pix_fmt rgba -start_number 0 tmp\\scene-0-%012d.raw'
}
{
  cmd: 'ffmpeg -i ./dir/1.mp4 -y -pix_fmt rgba -start_number 0 tmp\\scene-1-%012d.raw'
}
ffmpeg-concat: 900.884ms
(node:8384) UnhandledPromiseRejectionWarning: Error: ffmpeg exited with code 1: av_interleaved_write_frame(): I/O error
frame=    5 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.05 bitrate=N/A dup=4 drop=0 speed=5.57x
video:4133kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

    at ChildProcess.<anonymous> (C:\dir\node_modules\fluent-ffmpeg\lib\processor.js:182:22)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
(node:8384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Any idea what's going on?

**Comment by transitive-bullshit** [comment]
The filenames ending in ".gif" vs ".mp4" shouldn't matter -- they're passed as-is to ffmpeg and ffmpeg is smart at figuring out the underlying content-type of the data it's passed.

I've debugged the problem and am 99% sure you're seeing this because ffmpeg is bailing on account of the custom `tempDir` you're passing in not existing.

I've added more robustness around this as well as adding a `--verbose` option which should help to debug issues like this in the future.

Will be releasing these updates shortly.

**Comment by transitive-bullshit** [comment]
Just published v1.1.0 with a lot of related updates.

Note that you may want to upgrade Node.js versions to >= 13.7.0 if you are using macOS due to this downstream [bug](https://github.com/stackgl/headless-gl#supported-platforms-and-nodejs-versions) in Node.js.

**Comment by anonymousperson1209** [comment]
The errors are gone now, but this still isn't really working. Here's my test:

``` javascript
const concat = require('ffmpeg-concat');

(async () => {
    await concat({
        output: 'output.mp4',
        videos: [
            'https://external-preview.redd.it/2HHZCLTRYST_QVUI0-cP7ltzQoc3-qvOXfq_OIf8Igw.gif?format=mp4&s=28def085a8d274cb33d945ab996305aeaeb649b6',
            'https://external-preview.redd.it/t88brB8k6nI_btFV2IJ41l4ru78rwPVZ2orLasoj-zs.gif?format=mp4&s=eeb5f85df9c21ae6becba7d6abcbb287522c7fb5',
            'https://external-preview.redd.it/I6fzne5zHlx33IjiYnZOxUXZHHHjpOFYompT7z-_Uco.gif?format=mp4&s=dc6098c8f84e1bc3baf9ea63ce55e6ad13532ec5',
            'https://external-preview.redd.it/P9jbgsWUm7heVR7Fzqu7i9jfZLX-gIxtFqJ82KW6AZ0.gif?format=mp4&s=5115f98c3e65a230ae5281c48f01c982d4abc1cb',
            'https://external-preview.redd.it/b9L426fTDYQpc7cyzbQBmoI8Xw0Fj67FMPaMyvY64jY.gif?format=mp4&s=8d89a58289e3156a1a2495d260fa10ed59e4ac4e',
            'https://external-preview.redd.it/bWoFzIg3cXQkNMXyMpFIaB3-gb7uQepGLH3D4t2PjKw.gif?format=mp4&s=bd5a0b890a54c5a4eb7fda6dfd83a121ba4f07dd',
            'https://external-preview.redd.it/BLKztcSY07uG341SsKmJk5upmBUcYXoylJmcYoQocGw.gif?format=mp4&s=354b36b5025b57bf8c04ae627e18d708a0db2025',
            'https://external-preview.redd.it/KCCINYTFvtnbTKRdBGqyvcqdw9MRmmND14zjQpuXwXY.gif?format=mp4&s=31c02e90ebc5e84663f841389c3311a9d5df8377',
            'https://external-preview.redd.it/uhQNwXq6QzlOsaOb8cD8ZJbr7ExVvoktp4yRM_tTxMI.gif?format=mp4&s=48d2ab290d4ea795c5c1feb1026f76d7df61d52c',
            'https://external-preview.redd.it/LvPzIeKOS9ZX1a3EODvbQcUYlB6tE_psP7dyH1Yylm0.gif?format=mp4&s=20554c4e001259d3b172f81be73e3a1c839a9b31',
            'https://external-preview.redd.it/tMakGvj2Ra7EyHyhDdumP9xH-iEi8k5hq30nl05H6f8.gif?format=mp4&s=5bd64ba2d8dcb3766af1700b429179e28de2a217',
            'https://external-preview.redd.it/v-w11NDqvEJnR0zstT6jgzrNsuXSDYtD1zF93RxmY6Y.gif?format=mp4&s=61d123f9633fbcb3b3b6cb8ac6fee767bfa27bce',
            'https://external-preview.redd.it/7kwj501VYoECXcLd2p6GeHoyDqt566LkQDq39swP1uQ.gif?format=mp4&s=ec6d25cf1590abc2c7faff732bd8ecfea68ebf89',
            'https://external-preview.redd.it/eVsqo046dzE4s67nOHZJh7fdjUuqhOdKB34Z1UMdWlU.gif?format=mp4&s=5f519e6cbfebd85412a4e2fbe462f202fe3d60e5'
        ],
        transition: {
            name: 'directionalwipe',
            duration: 500
        },
        tempDir: 'tmp'
    });
})();
```
It works, but:
1. It takes a long time: about 15-20 minutes. Do know of any ways I can shorten this time a bit?
1. The resulting video has issues. Some clips play in slow motion, some are just a single freeze frame from he video, and others just show up as static.

I remember it being mentioned that all the video properties are decided based on the first video in the array. So my thought is to download a 0.5 sec, 60 fps, 1080p, all black video and set that as the first video in the array. I call the video `leader.mp4`. When I employ this strategy, I get:
```
(node:13076) UnhandledPromiseRejectionWarning: Error: Unsupported input video format "mov,mp4,m4a,3gp,3g2,mj2": leader.mp4
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:13076) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13076) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I greatly appreciate any help.

**Comment by mifi** [comment]
For anyone interested, I created a tool which is similar to this one, which does everything using streaming, thereby removing the need for temporary files and allowing much faster conversion, and has a lot more features. Hopefully useful for some of you: https://github.com/mifi/editly

**Comment by RubenJesusAzevedo** [comment]
I am trying to make a video from external videos.
Is working fine locally but in prod give me this error.

Someone can help me.

```
fmpeg-concat: 23.162ms
api_1            | Error: spawn ffprobe ENOENT
api_1            |     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
api_1            |     at onErrorNT (internal/child_process.js:469:16)
api_1            |     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
api_1            |   errno: 'ENOENT',
api_1            |   code: 'ENOENT',
api_1            |   syscall: 'spawn ffprobe',
api_1            |   path: 'ffprobe',
api_1            |   spawnargs: [
api_1            |     '-print_format',
api_1            |     'json',
api_1            |     '-show_error',
api_1            |     '-show_format',
api_1            |     '-show_streams',
api_1            |     'https://server.com/videos/assets/video.mp4'
api_1            |   ],
api_1            |   stdout: '',
api_1            |   stderr: '',
api_1            |   failed: true,
api_1            |   signal: null,
api_1            |   cmd: 'ffprobe -print_format json -show_error -show_format -show_streams https://server.com/videos/assets/video.mp4',
api_1            |   timedOut: false,
api_1            |   killed: false
api_1            | }
```

**Comment by transitive-bullshit** [comment]
@RubenJesusAzevedo please open a new issue and include reproduction steps. E.g., how are you invoking ffmpeg-concat exactly?
