### ISSUE TITLE
audioConcat.txt: No such file or directory

### ISSUE THREAD

**Issue by pixelzerg** [transitive-bullshit/ffmpeg-concat#72]
The ffmpeg-concat CLI gives an error when trying to concat two clips

Command:
```
ffmpeg-concat -t fade clips/000011.mp4 clips/000047.mp4 -O tmp -o out/out.mp4
```

Output:
```
{
  cmd: 'ffmpeg -i clips/000011.mp4 -y -loglevel info -pix_fmt rgba -start_number 0 tmp/scene-0-%012d.raw'
}
{
  cmd: 'ffmpeg -i clips/000047.mp4 -y -loglevel info -pix_fmt rgba -start_number 0 tmp/scene-1-%012d.raw'
}
{
  cmd: 'ffmpeg -ss 0.25 -i clips/000047.mp4 -y -acodec libmp3lame -vn -t 17.576 tmp/scene-1.mp3'
}
{
  cmd: 'ffmpeg -i clips/000011.mp4 -y -acodec libmp3lame -vn -t 17.843 tmp/scene-0.mp3'
}
init-frames: 24.826s
render 0%
render 1%
render 2%
render 2%
render 3%
render 4%
render 5%
render 5%
render 6%
render 7%
render 8%
render 8%
render 9%
render 10%
render 11%
render 11%
render 12%
render 13%
render 14%
render 14%
render 15%
render 16%
render 17%
render 17%
render 18%
render 19%
render 20%
render 20%
render 21%
render 22%
render 23%
render 23%
render 24%
render 25%
render 26%
render 26%
render 27%
render 28%
render 29%
render 29%
render 30%
render 31%
render 32%
render 32%
render 33%
render 34%
render 35%
render 35%
render 36%
render 37%
render 38%
render 38%
render 39%
render 40%
render 41%
render 41%
render 42%
render 43%
render 44%
render 44%
render 45%
render 46%
render 47%
render 47%
render 48%
render 49%
render 50%
render 50%
render 51%
render 52%
render 53%
render 54%
render 54%
render 55%
render 56%
render 57%
render 57%
render 58%
render 59%
render 60%
render 60%
render 61%
render 62%
render 63%
render 63%
render 64%
render 65%
render 66%
render 66%
render 67%
render 68%
render 69%
render 69%
render 70%
render 71%
render 72%
render 72%
render 73%
render 74%
render 75%
render 75%
render 76%
render 77%
render 78%
render 78%
render 79%
render 80%
render 81%
render 81%
render 82%
render 83%
render 84%
render 84%
render 85%
render 86%
render 87%
render 87%
render 88%
render 89%
render 90%
render 90%
render 91%
render 92%
render 93%
render 93%
render 94%
render 95%
render 96%
render 96%
render 97%
render 98%
render 99%
render 99%
render-frames: 2.530s
created tmp/audioConcat.txt
ffmpeg -f concat -safe 0 -i tmp/audioConcat.txt -y tmp/audioConcat.mp3
failed to concat audio Error: ffmpeg exited with code 1: tmp/audioConcat.txt: No such file or directory

    at ChildProcess.<anonymous> (/usr/lib/node_modules/ffmpeg-concat/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)  ffmpeg version n4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.3.0 (Arch Linux 9.3.0-1)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[concat @ 0x55fa86f981c0] Impossible to open 'tmp/tmp/scene-0.mp3'
tmp/audioConcat.txt: No such file or directory

ffmpeg-concat: 27.802s
concat error Error: ffmpeg exited with code 1: tmp/audioConcat.txt: No such file or directory

    at ChildProcess.<anonymous> (/usr/lib/node_modules/ffmpeg-concat/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
(node:62502) UnhandledPromiseRejectionWarning: Error: ffmpeg exited with code 1: tmp/audioConcat.txt: No such file or directory

    at ChildProcess.<anonymous> (/usr/lib/node_modules/ffmpeg-concat/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
(node:62502) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:62502) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by swlemp** [comment]
@pixelzerg If you set `cleanupFrames` to false, does that fix it?

**Comment by swlemp** [comment]
See #78
