### ISSUE TITLE
Could not locate the bindings file.

### ISSUE THREAD

**Issue by eqy** [transitive-bullshit/ffmpeg-concat#88]
Hi, I'm trying to using `ffmpeg-concat` from the command-line in Ubuntu 18.04 but I'm getting
```
/usr/local/lib/node_modules/ffmpeg-concat/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/build/webgl.node
 → /usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/build/Debug/webgl.node
 → /usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/build/Release/webgl.node
 → /usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/out/Debug/webgl.node
 → /usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/Debug/webgl.node
 → /usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/out/Release/webgl.node
 → /usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/Release/webgl.node
 → /usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/build/default/webgl.node
 → /usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/compiled/10.19.0/linux/x64/webgl.node
 → /usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/addon-build/release/install-root/webgl.node
 → /usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/addon-build/debug/install-root/webgl.node
 → /usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/addon-build/default/install-root/webgl.node
 → /usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/lib/binding/node-v64-linux-x64/webgl.node
    at bindings (/usr/local/lib/node_modules/ffmpeg-concat/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/src/javascript/native-gl.js:1:40)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/src/javascript/webgl-rendering-context.js:4:58)
```
I installed with `npm install -g`, but am I missing gl or some dependency somehow? Thanks.
I noticed another issue that suggested installing Xvfb and libmesa, but this did not seem to alleviate the problem. If it is relevant, I am running this on a machine with a GPU, but over ssh. `glxinfo` works in the terminal that I am using.

**Comment by eqy** [comment]
It turned out to be an underlying install issue.
Fixed after this:
https://stackoverflow.com/a/54170648/2790142
