### ISSUE TITLE
ffmpeg-concat CLI stops with syntax error

### ISSUE THREAD

**Issue by ProConEmu** [transitive-bullshit/ffmpeg-concat#9]
I ran the "npm install -g ffmpeg-concat" without error on my Linux Mint 17 system and then tried running the example ffmpeg-concat command with local files and got the following:

ffmpeg-concat -t circleopen -d 1000 -o test.wmv TOV.wmv TOV2.wmv
/home/gtaylor/.nvm/versions/node/v6.10.2/lib/node_modules/ffmpeg-concat/lib/index.js:12
module.exports = async (opts) => {
                       ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/gtaylor/.nvm/versions/node/v6.10.2/lib/node_modules/ffmpeg-concat/index.js:4:18)

**Comment by transitive-bullshit** [comment]
This package requires `node >= 8`.
