### ISSUE TITLE
ffmpeg exited with code 69: Conversion failed!

### ISSUE THREAD

**Issue by beshoo** [transitive-bullshit/ffmpeg-concat#94]
hello all,
I am trying to combine 4 videos, each one has different dimensions. I end with this error:

ffmpeg-concat -t CrossZoom -d 1000 -o output.mp4 funnymemzy.mp4 6790483283961498886.mp4 6850782378860842245.mp4 6836140888356343045.mp4
{
  cmd: 'ffmpeg -i funnymemzy.mp4 -y -loglevel info -pix_fmt rgba -start_number 0 /exe_tmp/445ea4f89d6fb25a7c6042f8b3733877/scene-0-%012d.raw'
}
{
  cmd: 'ffmpeg -i 6850782378860842245.mp4 -y -loglevel info -pix_fmt rgba -start_number 0 /exe_tmp/445ea4f89d6fb25a7c6042f8b3733877/scene-2-%012d.raw'
}
{
  cmd: 'ffmpeg -i 6790483283961498886.mp4 -y -loglevel info -pix_fmt rgba -start_number 0 /exe_tmp/445ea4f89d6fb25a7c6042f8b3733877/scene-1-%012d.raw'
}
{
  cmd: 'ffmpeg -i 6836140888356343045.mp4 -y -loglevel info -pix_fmt rgba -start_number 0 /exe_tmp/445ea4f89d6fb25a7c6042f8b3733877/scene-3-%012d.raw'
}
{
  cmd: 'ffmpeg -ss 0.5 -i 6850782378860842245.mp4 -y -acodec libmp3lame -vn -t 8 /exe_tmp/445ea4f89d6fb25a7c6042f8b3733877/scene-2.mp3'
}
{
  cmd: 'ffmpeg -ss 0.5 -i 6836140888356343045.mp4 -y -acodec libmp3lame -vn -t 9.567 /exe_tmp/445ea4f89d6fb25a7c6042f8b3733877/scene-3.mp3'
}
{
  cmd: 'ffmpeg -ss 0.5 -i 6790483283961498886.mp4 -y -acodec libmp3lame -vn -t 15.100000000000001 /exe_tmp/445ea4f89d6fb25a7c6042f8b3733877/scene-1.mp3'
}
init-frames: 3886.996ms
render 0%
render 1%
render 3%
render 4%
render 5%
render 6%
render 8%
render 9%
render 10%
render 11%
render 13%
render 14%
render 15%
render 16%
render 18%
render 19%
render 22%
render 20%
render 23%
render 24%
render 25%
render 27%
render 28%
render 29%
render 30%
render 32%
render 33%
render 34%
render 35%
render 37%
render 38%
render 39%
render 40%
render 42%
render 43%
render 44%
render 46%
render 47%
render 48%
render 49%
render 51%
render 52%
render 53%
render 54%
render 56%
render 57%
render 58%
render 59%
render 61%
render 62%
render 63%
render 65%
render 66%
render 67%
render 68%
render 70%
render 71%
render 72%
render 73%
render 75%
render 77%
render 76%
render 78%
render 80%
render 81%
render 82%
render 83%
render 85%
render 86%
render 87%
render 89%
render 90%
render 91%
render 92%
render 94%
render 95%
render 96%
render 97%
render 99%
render 100%
render-frames: 19526.146ms
render-audio: 0.046ms
{
  cmd: 'ffmpeg -framerate 25 -vcodec rawvideo -pixel_format rgba -video_size 1280x720 -i /exe_tmp/445ea4f89d6fb25a7c6042f8b3733877/%012d.raw -y -hide_banner -map_metadata -1 -map_chapters -1 -c:v libx264 -profile:v main -preset medium -crf 20 -movflags faststart -pix_fmt yuv420p -r 25 output.mp4'
}
transcode 0%
transcode 3%
transcode 5%
transcode 11%
transcode 16%
transcode 19%
transcode 59%
transcode 81%
transcode 91%
ffmpeg-concat: 31166.404ms
concat error Error: ffmpeg exited with code 69: Conversion failed!

    at ChildProcess.<anonymous> (/usr/local/lib/nodejs/lib/node_modules/ffmpeg-concat/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
(node:17615) UnhandledPromiseRejectionWarning: Error: ffmpeg exited with code 69: Conversion failed!

    at ChildProcess.<anonymous> (/usr/local/lib/nodejs/lib/node_modules/ffmpeg-concat/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
(node:17615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17615) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[MAX]root:[/home/beshoo/www/cat]

**Comment by wajdyz** [comment]
The same here, once i add 5 videos ore more i get this error
