### ISSUE TITLE
docker image not working

### ISSUE THREAD

**Issue by RubenJesusAzevedo** [transitive-bullshit/ffmpeg-concat#97]
**What  i'm using**
node -v v12.18.3
docker linux
yarn -v 1.22.4

**My Dockerfile**
```
FROM node:12-alpine
WORKDIR /usr/api
COPY package.json yarn.lock

RUN apk add --no-cache --virtual libxext-dev pkgconfig python make g++ #without this line, give me gyp Err! not ok

RUN yarn 
COPY  . .
EXPOSE 3000
CMD ["yarn", "start"]
```
**The Code**
```
  videos = [
  'https://myserver.com/my_video.mp4',
   'https://myserver.com/my_video2.mp4',
   'https://myserver.com/my_video3.mp4'
 ]

transitions = [
        {
            "name": "SimpleZoom",
            "duration": 1000
        },
        {
            "name": "CrossZoom",
            "duration": 500
        }]
return new Promise((resolve, reject) => {
    concat({
      output: `output.mp4`,
      videos: videos,
      transitions: transitions
    })
      .then(() => resolve(true))
      .catch((err) => reject(err))
  })
```

**ERROR**
```
ffmpeg-concat: 150.876ms
api_1  | Error: spawn ffprobe ENOENT
api_1  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
api_1  |     at onErrorNT (internal/child_process.js:469:16)
api_1  |     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
api_1  |   errno: 'ENOENT',
api_1  |   code: 'ENOENT',
api_1  |   syscall: 'spawn ffprobe',
api_1  |   path: 'ffprobe',
api_1  |   spawnargs: [
api_1  |     '-print_format',
api_1  |     'json',
api_1  |     '-show_error',
api_1  |     '-show_format',
api_1  |     '-show_streams',
api_1  |     'https://myserver.com/my_video.mp4'
api_1  |   ],
api_1  |   stdout: '',
api_1  |   stderr: '',
api_1  |   failed: true,
api_1  |   signal: null,
api_1  |   cmd: 'ffprobe -print_format json -show_error -show_format -show_streamshttps://myserver.com/my_video.mp4',
api_1  |   timedOut: false,
api_1  |   killed: false
api_1  | }
```

In dev is everything working fine. So i think the problem is create the docker image.

Maybe the line in my DockerFile -> "RUN apk add --no-cache --virtual libxext-dev pkgconfig python make g++"
is not resolving my problem.

Without the libxext-dev give me this error

```
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
Package 'x11', required by 'virtual:world', not found
Package 'xi', required by 'virtual:world', not found
Package 'xext', required by 'virtual:world', not found
gyp: Call to 'pkg-config --libs-only-l x11 xi xext' returned exit status 1 while in angle/src/angle.gyp. while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/api/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.128-microsoft-standard
gyp ERR! command "/usr/local/bin/node" "/usr/api/node_modules/gl/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/api/node_modules/gl
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v7.1.0
gyp ERR! not ok
```
What i'm doing wrong?

**Comment by georgeevans1995** [comment]
Hi @RubenJesusAzevedo, did you find a solution to this error? Having the same problem.

**Comment by RubenJesusAzevedo** [comment]
> Hi @RubenJesusAzevedo, did you find a solution to this error? Having the same problem.

I change my docker container and make this work.
Hope this helps.
```
FROM nikolaik/python-nodejs:python3.8-nodejs14
WORKDIR /usr/api

COPY package.json yarn.lock

RUN apt-get update
RUN apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config
RUN apt-get install -y ffmpeg

RUN apt-get install -y dumb-init xvfb
RUN chmod 0777 /usr/bin/dumb-init

ENTRYPOINT ["/usr/bin/dumb-init", "--", "xvfb-run", "-s", "-ac -screen 0 1920x1080x24"]
RUN yarn

COPY  . .

EXPOSE 3000
CMD ["yarn", "start"]
```

**Comment by georgeevans1995** [comment]
Thanks for replying, I downgraded my node alpine version to node:12-alpine and that seems to have fixed it for me.

**Comment by georgeevans1995** [comment]
Scrap my last comment, it was building fine with but didn't actually run in production, your file works a charm, thanks!
